apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploy/deployment.yaml
  - deploy/service.yaml
  #- deploy/ingress.yaml

images:
  - name: cepgstapacr.azurecr.io/82023066/healthcheck
    newTag: v1.0.2