name: CI and CD(azure CLI)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Upload JAR file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: ./java-app

      - name: Install Azure CLI
        uses: azure/CLI@v1

      - name: Upload artifact to VM and restart service
        env:
          AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
          AZURE_USERNAME: ${{ secrets.AZURE_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key.pem
          chmod 600 private_key.pem

          # Copy the JAR file to the VM
          scp -i private_key.pem -o StrictHostKeyChecking=no ./java-app/*.jar $AZURE_USERNAME@$AZURE_VM_IP:/path/to/deploy/

          # Restart the service on the VM
          ssh -i private_key.pem -o StrictHostKeyChecking=no $AZURE_USERNAME@$AZURE_VM_IP 'sudo systemctl restart my-java-app'

          # Clean up
          rm private_key.pem
